# https://github.com/elastic/logstash-docker
FROM logstash:6.8.3

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-input-http